using System;
using System.Collections.Generic;
using System.Text;

namespace AttributesSourceGeneratorHelper;

public partial class SampleAttribute
{
    //this is autogenerated.
    //obviously has to be sent to the client though so they know its required (if any)

    //if none is required, this would not be done.
    
    public SampleAttribute(int firstValue, int thirdValue)
    {
        FirstValue = firstValue;
        ThirdValue = thirdValue;
    }
}
