using SourceGeneratorsAttributesLibrary;
namespace AttributesSourceGeneratorHelper;
[AttributeUsage(AttributeTargets.Class)]
public partial class SampleAttribute : Attribute
{
    [Required]
    public int FirstValue { get; set; }
    public int SecondValue { get; set; }
    [Required]
    public int ThirdValue { get; set; }
    //if required, then do this part.
    //if no required, then ignore any extras.

    //we need the variable type.
    //also, the first letter has to be lower case as well.

    //this part is autogenerated.

}
